apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.application.name }}-pv
    labels:
        app: {{ .Values.application.name}}
spec:
    storageClassName: {{ .Values.volume.storageClassName }}
    capacity:
        storage: {{ .Values.volume.storagePV }}
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/data"
    # awsElasticBlockStore:
    #     fsType: "ext4"
    #     volumeID: "ID from aws ebs"
