apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.application.name }}-pvc
spec:
    storageClassName: {{ .Values.volume.storageClassName }}
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.volume.storagePVC }}